import React, { createContext, useContext, useState, useEffect } from 'react'

const LangContext = createContext()

const TRANSLATIONS = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    portfolio: 'Portfolio',
    overview: 'Overview',
    assessments: 'Assessments',
    signOut: 'Sign Out',
    // Dashboard
    welcome: 'Welcome back',
    yourXP: 'Your XP',
    takeAssessment: 'Take Assessment',
    viewResults: 'View Results',
    noAssessments: 'No assessments available',
    // Assessment
    submit: 'Submit',
    next: 'Next Question',
    previous: 'Previous',
    submitting: 'Submitting...',
    timeRemaining: 'Time Remaining',
    recordAudio: 'Record Audio',
    recordVideo: 'Record Video',
    stopRecording: 'Stop Recording',
    getFollowup: 'Get Follow-up Challenge',
    generating: 'Generating...',
    followupChallenge: 'Follow-up Challenge',
    wordsCount: 'words',
    answered: 'answered',
    // Results
    results: 'Assessment Results',
    score: 'Score',
    integrity: 'Integrity',
    xpEarned: 'XP Earned',
    confidence: 'Confidence',
    question: 'Question',
    aiDetection: 'AI Detection',
    aiPhrases: 'AI phrases detected',
    integrityFlags: 'Integrity Flags',
    learningPath: 'Your Personalized Learning Path',
    skillGaps: 'Skill Gaps Identified',
    recommendedActivities: 'Recommended Activities',
    generateCert: 'Generate Certificate',
    generatingCert: 'Generating Certificate...',
    certGenerated: 'Certificate Generated!',
    downloadCert: 'Download Certificate',
    backToDashboard: 'Back to Dashboard',
    // Certificate
    blockchainVerified: 'Blockchain-Verified Certificate',
    verifyOn: 'Verify authenticity',
    issuedOn: 'Issued',
    certHash: 'Certificate Hash',
    // Portfolio
    mySubmissions: 'My Submissions',
    myCertificates: 'My Certificates',
    noCertificates: 'No certificates yet',
    // Auth
    signIn: 'Sign In',
    createAccount: 'Create Free Account',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    student: 'Student / Candidate',
    teacher: 'Teacher / HR Admin',
    iAmA: 'I am a...',
    haveAccount: 'Have an account?',
    noAccount: "Don't have an account?",
    demoStudent: 'Demo Student',
    demoAdmin: 'Demo Admin',
    // Language
    language: 'Language',
    english: 'English',
    hindi: 'Hindi',
    marathi: 'Marathi',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    portfolio: 'पोर्टफोलियो',
    overview: 'अवलोकन',
    assessments: 'मूल्यांकन',
    signOut: 'साइन आउट',
    welcome: 'वापस स्वागत है',
    yourXP: 'आपका XP',
    takeAssessment: 'मूल्यांकन लें',
    viewResults: 'परिणाम देखें',
    noAssessments: 'कोई मूल्यांकन उपलब्ध नहीं',
    submit: 'जमा करें',
    next: 'अगला प्रश्न',
    previous: 'पिछला',
    submitting: 'जमा हो रहा है...',
    timeRemaining: 'शेष समय',
    recordAudio: 'ऑडियो रिकॉर्ड करें',
    recordVideo: 'वीडियो रिकॉर्ड करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    getFollowup: 'अनुवर्ती चुनौती प्राप्त करें',
    generating: 'उत्पन्न हो रहा है...',
    followupChallenge: 'अनुवर्ती चुनौती',
    wordsCount: 'शब्द',
    answered: 'उत्तर दिया',
    results: 'मूल्यांकन परिणाम',
    score: 'स्कोर',
    integrity: 'अखंडता',
    xpEarned: 'अर्जित XP',
    confidence: 'आत्मविश्वास',
    question: 'प्रश्न',
    aiDetection: 'AI पहचान',
    aiPhrases: 'AI वाक्यांश पाए गए',
    integrityFlags: 'अखंडता चेतावनियाँ',
    learningPath: 'आपका व्यक्तिगत शिक्षण पथ',
    skillGaps: 'पहचाने गए कौशल अंतराल',
    recommendedActivities: 'अनुशंसित गतिविधियाँ',
    generateCert: 'प्रमाणपत्र बनाएं',
    generatingCert: 'प्रमाणपत्र बन रहा है...',
    certGenerated: 'प्रमाणपत्र बनाया गया!',
    downloadCert: 'प्रमाणपत्र डाउनलोड करें',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    blockchainVerified: 'ब्लॉकचेन-सत्यापित प्रमाणपत्र',
    verifyOn: 'प्रामाणिकता सत्यापित करें',
    issuedOn: 'जारी',
    certHash: 'प्रमाणपत्र हैश',
    mySubmissions: 'मेरे जमा किए गए',
    myCertificates: 'मेरे प्रमाणपत्र',
    noCertificates: 'अभी तक कोई प्रमाणपत्र नहीं',
    signIn: 'साइन इन',
    createAccount: 'मुफ्त खाता बनाएं',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    student: 'छात्र / उम्मीदवार',
    teacher: 'शिक्षक / HR व्यवस्थापक',
    iAmA: 'मैं हूं...',
    haveAccount: 'खाता है?',
    noAccount: 'खाता नहीं है?',
    demoStudent: 'डेमो छात्र',
    demoAdmin: 'डेमो व्यवस्थापक',
    language: 'भाषा',
    english: 'अंग्रेज़ी',
    hindi: 'हिन्दी',
    marathi: 'मराठी',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    portfolio: 'पोर्टफोलिओ',
    overview: 'आढावा',
    assessments: 'मूल्यांकन',
    signOut: 'साइन आउट',
    welcome: 'पुन्हा स्वागत',
    yourXP: 'तुमचा XP',
    takeAssessment: 'मूल्यांकन घ्या',
    viewResults: 'निकाल पहा',
    noAssessments: 'कोणतेही मूल्यांकन उपलब्ध नाहीत',
    submit: 'सादर करा',
    next: 'पुढचा प्रश्न',
    previous: 'मागील',
    submitting: 'सादर होत आहे...',
    timeRemaining: 'उर्वरित वेळ',
    recordAudio: 'ऑडिओ रेकॉर्ड करा',
    recordVideo: 'व्हिडिओ रेकॉर्ड करा',
    stopRecording: 'रेकॉर्डिंग थांबवा',
    getFollowup: 'अनुसरण आव्हान मिळवा',
    generating: 'तयार होत आहे...',
    followupChallenge: 'अनुसरण आव्हान',
    wordsCount: 'शब्द',
    answered: 'उत्तर दिले',
    results: 'मूल्यांकन निकाल',
    score: 'गुण',
    integrity: 'सचोटी',
    xpEarned: 'मिळालेला XP',
    confidence: 'आत्मविश्वास',
    question: 'प्रश्न',
    aiDetection: 'AI ओळख',
    aiPhrases: 'AI वाक्प्रचार आढळले',
    integrityFlags: 'सचोटी इशारे',
    learningPath: 'तुमचा वैयक्तिक शिक्षण मार्ग',
    skillGaps: 'ओळखलेल्या कौशल्य कमतरता',
    recommendedActivities: 'शिफारस केलेल्या क्रिया',
    generateCert: 'प्रमाणपत्र तयार करा',
    generatingCert: 'प्रमाणपत्र तयार होत आहे...',
    certGenerated: 'प्रमाणपत्र तयार झाले!',
    downloadCert: 'प्रमाणपत्र डाउनलोड करा',
    backToDashboard: 'डॅशबोर्डवर परत जा',
    blockchainVerified: 'ब्लॉकचेन-सत्यापित प्रमाणपत्र',
    verifyOn: 'सत्यता पडताळा',
    issuedOn: 'जारी',
    certHash: 'प्रमाणपत्र हॅश',
    mySubmissions: 'माझे सादरीकरण',
    myCertificates: 'माझी प्रमाणपत्रे',
    noCertificates: 'अद्याप प्रमाणपत्र नाहीत',
    signIn: 'साइन इन',
    createAccount: 'मोफत खाते तयार करा',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूर्ण नाव',
    student: 'विद्यार्थी / उमेदवार',
    teacher: 'शिक्षक / HR व्यवस्थापक',
    iAmA: 'मी आहे...',
    haveAccount: 'खाते आहे?',
    noAccount: 'खाते नाही?',
    demoStudent: 'डेमो विद्यार्थी',
    demoAdmin: 'डेमो व्यवस्थापक',
    language: 'भाषा',
    english: 'इंग्रजी',
    hindi: 'हिंदी',
    marathi: 'मराठी',
  }
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('sf_lang') || 'en')

  useEffect(() => {
    localStorage.setItem('sf_lang', lang)
  }, [lang])

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
